### ISSUE TITLE
CD Incorrect Directory

### ISSUE THREAD

**Issue by EaganFarlin** [MicrosoftLearning/mslearn-ai-services#11]
Regarding [Manage Azure AI Services Security](https://github.com/MicrosoftLearning/mslearn-ai-services/blob/main/Instructions/Exercises/02-ai-services-security.md).

_[Use the service principal in an application](https://github.com/MicrosoftLearning/mslearn-ai-services/blob/main/Instructions/Exercises/02-ai-services-security.md#use-the-service-principal-in-an-application)_
...
1. _In your terminal, switch to the C-Sharp or Python folder depending on your language preference. By running cd C-Sharp or cd Python. Then run `cd keyvault_client`._

For Python developers, the correct directory would be `cd keyvault-client`.

**Comment by ivorb** [comment]
fixed with your PR
