### ISSUE TITLE
In lab no reminder to register the resource provider

### ISSUE THREAD

**Issue by wbpluto** [MicrosoftLearning/mslearn-ai-services#16]
https://github.com/MicrosoftLearning/mslearn-ai-services/blob/main/Instructions/Exercises/01-use-azure-ai-services.md

In lab no reminder to register the resource provider. But in fact by default you can't create AI service resources, you need to register the resource provider for cognitive services beforehand
![ai lab issue 001](https://github.com/MicrosoftLearning/mslearn-ai-services/assets/5191513/8dea04d7-cfc8-434a-86fa-932dfd463ddb)

**Comment by ivorb** [comment]
I'm not reproducing this in the hosted environment. Please reopen an issue if it's still an issue, and provide more details (such as if this is a skillable env, which it appears to be, and if you reproduce). It's possible the sub you got was brand new and a 1-off issue, in which case your instructor should be able to help you.
