### ISSUE TITLE
Doesn't support .net core 8

### ISSUE THREAD

**Issue by XUTProf** [MicrosoftLearning/mslearn-ai-services#19]
I'm on OSX using brew to install/maintain dotnet. i.e. brew install dotnet.  
However, brew only has 8.0.1 and this code is still on version 7.0.0, which will be out of support by this May.
Since brew doesn't support version 7 (brew install dotnet@7.0.0), I had to remove net8 and "hard" install net7. 
Can this sample be upgraded to version 8 soon?
thanks,
Stuart Ngai.

**Comment by ivorb** [comment]
Feedback is noted, however these labs are built to run on our hosted environment that uses 7. Updates to 8 will have to coincide with updates to that environment. We will update these as appropriate
