### ISSUE TITLE
Confusing line in 04 and 03 instructions

### ISSUE THREAD

**Issue by SLejmialight** [MicrosoftLearning/mslearn-ai-services#20]
I spent some time trying to figure out why the cloned repository did not contain a c# and python folder like 01 and 02. 
![image](https://github.com/MicrosoftLearning/mslearn-ai-services/assets/153204699/29a69bc2-7149-4e26-8c5d-70b010e451e5)

I think that line should be removed for clarity.

**Comment by ivorb** [comment]
fixed
