### ISSUE TITLE
BUG -  to use the rest interface

### ISSUE THREAD

**Issue by seilorjunior** [MicrosoftLearning/mslearn-ai-services#21]
Following the docs.

- Using python i am getting the error ("The Detect Language Operation under Text Analytics API (v3.1) is not supported with the current subscription key and pricing tier OpenAI.S0.)
- Using C# this one 
StatusCode: 401, ReasonPhrase: 'Access Denied', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  apim-request-id: 52c36e73-48bb-48ef-b9a0-5e99a5d3e108
  apim-operation-name: Detect+Language
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  WWW-Authenticate: AzureApiManagementKey realm="https://xxxxx.openai.azure.com/text/analytics",name="Ocp-Apim-Subscription-Key",type="header"
  Date: Wed, 06 Mar 2024 19:28:16 GMT
  Content-Length: 178
  Content-Type: application/json

**Comment by ivorb** [comment]
it appears your configuration is incorrect, and you're trying to send a language detection call to an openai endpoint. Please follow the exercise steps exactly
