### ISSUE TITLE
The information about requirement of .NET Core 7.0 SDK and runtime is not valid anymore

### ISSUE THREAD

**Issue by eriawan** [MicrosoftLearning/mslearn-ai-services#26]
In the page of this: https://microsoftlearning.github.io/mslearn-ai-services/Instructions/setup.html

It says about needs .NET 7.0 SDK installed:

![image](https://github.com/MicrosoftLearning/mslearn-ai-services/assets/8773147/aa548c5d-ce1d-4111-8b4e-475a252a9062)

This is problematic because as of today, 28th May 2024, .NET 7.0 is out of support:
(source: https://dotnet.microsoft.com/en-us/download/dotnet)

![image](https://github.com/MicrosoftLearning/mslearn-ai-services/assets/8773147/0de036ba-c9ff-44ce-aa19-2fda1be33762)

Could the setup.md and the actual lab instruction be updated to at least use .NET 8.0, the STS version?

**Comment by ivorb** [comment]
The hosted labs are tested and verified against that environment, which is still on 7.0. Updating this is a bigger ask than just changing the setup file - I'll add notes in there about it for clarity, and have it on the backlog to update the .NET version on the VMs and test the code.
