### ISSUE TITLE
Use an Azure AI Services Container - cannot access Azure container

### ISSUE THREAD

**Issue by scottrhay** [MicrosoftLearning/mslearn-ai-services#29]
In the Use an Azure AI Services Container lab, I created both an Azure container, and a local docker container. 

I'm able to run the CURL command just fine with my localhost container instance, and it returns the languages of the content. 

However, when I use the Azure container, I always receive this error:  curl: (56) Recv failure: Connection was reset

I've created a second container, and it has the same issue. I've tried access with both IP and FQDN. 

Is anyone else aware of this issue and how to resolve it?

**Comment by ajparrah** [comment]
Hi, I have the same issue with this lab!

In fact, a local container either does not work for me.

The container gets up properly (On Azure container and localhost):

![image](https://github.com/MicrosoftLearning/mslearn-ai-services/assets/48602979/f2199fba-fdce-468a-9982-f277a9a3ca1e)

![image](https://github.com/MicrosoftLearning/mslearn-ai-services/assets/48602979/ad6ae87a-cd43-4786-82db-64c906cd472e)

But the endpoint that it provides us does not work. I get a response using `/status` only

![image](https://github.com/MicrosoftLearning/mslearn-ai-services/assets/48602979/979c10db-1ab1-497f-9f86-266250fe77e5)

**Comment by ivorb** [comment]
@afelix-95 can you take a look at this, as time allows?

**Comment by nidhichandra20** [comment]
Yes even I am facing the same issue , tried multiple times with different region of azure container instance ,nothing works .

**Comment by ivorb** [comment]
I recently had more success using a sentiment analysis container image - going to switch the lab to that today. Do report another issue if that doesn't improve the experience

**Comment by bkashefipour** [comment]
> I recently had more success using a sentiment analysis container image - going to switch the lab to that today. Do report another issue if that doesn't improve the experience

thanks for pointing it out ... sentiment analysis is the only one working for me now

**Comment by ivorb** [comment]
we've moved this to sentiment, and it tested smoothly. If you run into this issue again, please open a new issue for us to investigate
