### ISSUE TITLE
reset-test.sh Incorrect cURL Placeholder Value

### ISSUE THREAD

**Issue by tp1045** [MicrosoftLearning/mslearn-ai-services#6]
Small change is required, should read "yourkey"

https://github.com/MicrosoftLearning/mslearn-ai-services/blob/e1bec7eacb61decedfca4f59aefcab0f76d27579/Labfiles/02-ai-services-security/rest-test.sh#L1

`-H "Ocp-Apim-Subscription-Key: <your-endpoint>"` to `-H "Ocp-Apim-Subscription-Key: <your-key>"`

**Comment by ivorb** [comment]
fixed
