### ISSUE TITLE
Variable has been renamed

### ISSUE THREAD

**Issue by soderholmd** [MicrosoftLearning/mslearn-ai-services#9]
In lab 02, the .env file has the variable COG_SERVICE_ENDPOINT, but the .py file is reading AI_SERVICE_ENDPOINT. As such it fails with a 'endpoint name must be a string' error. Changing the variable name to AI_SERVICE_ENDPOINT in .env fixes this.

**Comment by ivorb** [comment]
fixed with recent PR merge
